### ISSUE TITLE
Incorrect language codes

### ISSUE THREAD

**Issue by johnfactotum** [kevinhendricks/KindleUnpack#35]
It seems that most of the region codes are wrong. E.g.
https://github.com/kevinhendricks/KindleUnpack/blob/c8be31a196fd92803f78ad34a3f18d40319bbac5/lib/mobi_utils.py#L36

I think the keys should be multiples of 4? That is, `4`, `8`, `12`, and `16` for `zh-TW`, `zh-CN`, `zh-HK`, `zh-SG`, respectively, not `1`, `2`, `3`, `4`.

The ones for Spanish seem to be the only ones that are correct:
https://github.com/kevinhendricks/KindleUnpack/blob/c8be31a196fd92803f78ad34a3f18d40319bbac5/lib/mobi_utils.py#L97-L99

**Comment by kevinhendricks** [comment]
There are actually two sets of mappings based on really old mobi or not. 

 I will take a look at how calibre does its mobi language code lookups and see if it can be improved.  It does work for multiple en based languages.  

Since they are factors of 4, my guess is they just need to be shifted right 2 more bits in some newer mobis to work correctly with this table.

**Comment by johnfactotum** [comment]
Thanks. I noticed this because using this table, some books have mismatched language codes between the MOBI header and the EXTH record 524. I guess that's another issue. Maybe it should just use the code from EXTH if available?

> Since they are factors of 4, my guess is they just need to be shifted right 2 more bits in some newer mobis to work correctly with this table.

It looks like it used to do that but it was changed in https://github.com/kevinhendricks/KindleUnpack/commit/d50335340b218127854dfe73da4024d217e121e0.

Either way, it seems there's some inconsistency between the Spanish part and the rest of the table.

**Comment by kevinhendricks** [comment]
Based on what we had previously (rotating 10 bits) is what calibre does today, I reverted that change from 2015 and them updated the es (Spanish) and a few other entries that seem to be based on 4 and not 1 to match.

This change should now make Chinese (zh-*) mappings work and not break en-* mappings and most others.

I really have no way to check if changing the Spanish ones is correct or not but my guess is they are now correct.

This change was pushed to master.  It should appear in the next official release but I am unsure of when that will be.

You should probably grab mobi_header.py and mobi_utils.py from current master to replace their namesakes until an official release is made.

I am closing this as now fixed in master, but feel free to comment here if needed and I will reopen it if this change does not fix your issue.
